"""Authentication, authorization, and secret-safe security primitives."""

from jarvis.security.desktop_auth import (
    AuthenticatedPrincipal,
    ContractRange,
    DesktopSessionAuthenticator,
    DesktopSessionRecord,
    DesktopSessionToken,
    DeviceRecord,
    DeviceStatus,
    InMemoryDeviceRegistry,
    InMemoryNonceStore,
    InMemorySessionRegistry,
    SessionStatus,
    authenticate_desktop_session,
    authenticateDesktopSession,
)
from jarvis.security.device_identity import (
    DeviceIdentity,
    DeviceIdentityConflictError,
    DeviceRegistrationError,
    DeviceRegistrationService,
    InMemoryDeviceIdentityRegistry,
    InteractiveUser,
    KeyProtection,
    WindowsCngDeviceKeyStore,
    WindowsInteractiveUserResolver,
    registerDeviceIdentity,
)

__all__ = [
    "AuthenticatedPrincipal",
    "ContractRange",
    "DesktopSessionAuthenticator",
    "DesktopSessionRecord",
    "DesktopSessionToken",
    "DeviceRecord",
    "DeviceStatus",
    "InMemoryDeviceRegistry",
    "InMemoryNonceStore",
    "InMemorySessionRegistry",
    "SessionStatus",
    "authenticate_desktop_session",
    "authenticateDesktopSession",
    "DeviceIdentity",
    "DeviceIdentityConflictError",
    "DeviceRegistrationError",
    "DeviceRegistrationService",
    "InMemoryDeviceIdentityRegistry",
    "InteractiveUser",
    "KeyProtection",
    "WindowsCngDeviceKeyStore",
    "WindowsInteractiveUserResolver",
    "registerDeviceIdentity",
]
